version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: "/api"
      NEXT_PUBLIC_WEBSITE_BASE_URL: "http://localhost:3000"
      MONGODB_NAME: "nextjs13-project"
      MONGODB_URI: "mongodb://mongodb:27017/$MONGODB_NAME"

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
